###
GET http://localhost:{{port}}/v1/healthcheck

###
POST http://localhost:{{port}}/v1/pages

###
GET http://localhost:{{port}}/v1/pages/12

###
GET http://localhost:{{port}}/v1/pages/foobar

###
GET http://localhost:{{port}}/v1/photos/1
