###
GET http://localhost:{{port}}/v1/healthcheck

###
POST http://localhost:{{port}}/v1/pages

###
GET http://localhost:{{port}}/v1/pages/12

###
GET http://localhost:{{port}}/v1/pages/foobar

###
GET http://localhost:{{port}}/v1/photos/1

###
PUT http://localhost:{{port}}/v1/photos/1

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo"
}

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo",
  "name2": "foo"
}

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo"
}

{
  "name": "foo2"
}
