###
GET http://localhost:{{port}}/v1/healthcheck

###
POST http://localhost:{{port}}/v1/pages

###
GET http://localhost:{{port}}/v1/pages/12

###
GET http://localhost:{{port}}/v1/pages/foobar

###
GET http://localhost:{{port}}/v1/photos/2

###
PUT http://localhost:{{port}}/v1/photos/1

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo"
}

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo",
  "name2": "foo"
}

###
POST http://localhost:{{port}}/v1/pages
Content-Type: application/json

{
  "name": "foo"
}

{
  "name": "foo2"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.error === "body must only contain a single JSON value", "Response body is not 'Invalid JSON'");
    });
%}

###
POST http://localhost:{{port}}/v1/photos
Content-Type: application/json

{
  "name": "A big cat"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}

###
POST http://localhost:{{port}}/v1/photos
Content-Type: application/json

{
  "name": "A small cat"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}

###
PUT http://localhost:{{port}}/v1/photos/3
Content-Type: application/json

{
  "name": "This is an update"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}
